version: "3.9"

name: ${APP_CONTAINER_NAME}-container-dev
services:
  node-server:
    environment:
      - NODE_ENV=dev
      - PORT=${PORT}
      - APP_NAME=${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: ${NODE_VERSION}
        PORT: ${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: ${APP_NAME}-Development
    expose:
      - ${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: npx ts-node-dev --poll --watch ./src/* --respawn ./src/server.ts
