FROM nginx:latest

COPY ./nginx/default.conf.template /etc/nginx/conf.d/default.conf.template

COPY ./nginx/entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
