version: "3.9"

name: ${APP_CONTAINER_NAME}-container-scale
services:
  node-server:
    environment:
      - NODE_ENV=prod
      - PORT=${PORT}
      - APP_NAME=${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile.scale
      args:
        NODE_VERSION: ${NODE_VERSION}
        PORT: ${PORT}
        APP_NAME: ${APP_NAME}
    volumes:
      - /usr/src/app
    command: npx ts-node ./src/server.ts

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - node-server
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env

  # Only applicable with container images
  # watchtower:
  #   image: containrrr/watchtower
  #   command:
  #     - "--label-enable"
  #     - "--interval"
  #     - "15"
  #     - "--rolling-restart"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  # CI/CD Pipeline
  # webhook-listener:
  #   image: almir/webhook
  #   environment:
  #     - WEBHOOK_URL_PATH=/webhook
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - .:/usr/src/app
  #     - ./hooks:/etc/webhook
  #   command:
  #     [
  #       "-hooks",
  #       "/etc/webhook/hooks.json",
  #       "-verbose",
  #       "-hotreload",
  #       "-urlprefix",
  #       "/webhook",
  #     ]
  #   depends_on:
  #     - node-server
  #     - nginx
