version: "3.9"

name: ${APP_CONTAINER_NAME}-container-prod
services:
  node-server:
    environment:
      - NODE_ENV=prod
      - PORT=${PORT}
      - APP_CONTAINER_NAME=${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NODE_VERSION: ${NODE_VERSION}
        PORT: ${PORT}
    volumes:
      - /usr/src/app
    container_name: ${APP_CONTAINER_NAME}-Production
    expose:
      - ${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: /bin/sh -c "sleep 20 && npx ts-node ./src/server.ts
    restart: unless-stopped
    networks:
      - main_network
    depends_on:
      - server-mysql

  mysql:
    image: mysql:8.0
    container_name: server-mysql
    restart: unless-stopped
    networks:
      - main_network
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Root password
      MYSQL_DATABASE: main_data # Default database
      MYSQL_USER: main_user # Non-root user
      MYSQL_PASSWORD: user_password # Non-root user password
    volumes:
      - mysql_data:/var/lib/mysql # Mounting persistent volume for data storage
    ports:
      - "3959:3306" # Expose port 3306 for MySQL

networks:
  main_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local # Use local storage for persistent data
