name: ${APP_CONTAINER_NAME}-container-prod
services:
  node-server:
    environment:
      - NODE_ENV=prod
      - PORT=${PORT}
      - APP_CONTAINER_NAME=${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NODE_VERSION: ${NODE_VERSION}
        PORT: ${PORT}
    volumes:
      - /usr/src/app
    container_name: ${APP_CONTAINER_NAME}-Production
    expose:
      - ${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: npx ts-node ./src/server.ts
    restart: unless-stopped
    networks:
      - main_network

  mysql:
    image: mysql:8.0
    container_name: server-mysql
    restart: unless-stopped
    networks:
      - main_network
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: main_data
      MYSQL_USER: main_user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3959:3306"

networks:
  main_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
